styles/lazy-styles.css, styles/styles.css
includes an initial version of #2 and #3
https://initial-default-styling--business-website--adobe.hlx3.page/drafts/uncled/blog/amplify-her-voice-womens-day
https://initial-default-styling--business-website--adobe.hlx3.page/drafts/uncled/blog/agility-empathy-purpose-steered-mastercard-during-pandemic
this one is more inspired by recent consonants work than by the current blog.adobe.com design but i think that should be ok to get started...
=> feat: initial styling setup

styles/styles.css
https://default-content-styling--business-website--adobe.hlx3.page/drafts/uncled/blog/kitchen-sink
trivial fix for issue reported by @seanchoi-workfront
=> fix(default-content): correct header selector

helix-query.yaml
=> feat(index): setup index

.github/workflows/psi.yml
Adding the Page Speed Insights Audit for pull requests.
See also: https://github.com/auniverseaway/helix-actions
As maintainers we want to know if a contribution reduces the performance of the site.
Integration test: https://github.com/auniverseaway/bel/pull/6#issuecomment-890254089
=> feat(psi): Add Helix PSI Action Workflow

blocks/article-header/article-header.css, blocks/article-header/article-header.js, scripts/scripts.js, styles/styles.css
https://autoblocking--business-website--adobe.hlx3.page/blog/trends/adobe-summit-2021-recap-look-whats-possible-with-experience-manager-now
https://autoblocking--business-website--adobe.hlx3.page/drafts/uncled/blog/kitchen-sink
=> feat: autoblocking refactor

.eslintrc.js, .github/workflows/run-tests.yaml, blocks/animation/animation.js, blocks/article-feed/article-feed.js, blocks/article-header/article-header.js, blocks/banner/banner.js, blocks/block-helpers.js, blocks/featured-article/featured-article.js, blocks/gnav/gnav.js, blocks/infographic/infographic.js, blocks/pull-quote/pull-quote.js, blocks/recommended-articles/recommended-articles.js, scripts/scripts.js, test/unit/blocks/blocks.test.js
=> chore: run linting on push

scripts/scripts.js
see issue here:
https://main--business-website--adobe.hlx3.page/blog/trends/amplify-her-voice-womens-day
fixed here:
https://autoblocking--business-website--adobe.hlx3.page/blog/trends/amplify-her-voice-womens-day
=> fix: special case with no sibling

scripts/scripts.js
support block variants...
https://block-variants--business-website--adobe.hlx3.page/drafts/uncled/blog/kitchen-sink
inital hack, this should probably be refactored.
=> feat: support block variants

blocks/gnav/gnav.css, blocks/gnav/gnav.js
=> fix(gnav): add esc and fix closing

index.md
Really just testing the Helix Action for PSI, but this probably isn't needed.
=> Remove index.md

blocks/article-feed/article-feed.css, blocks/article-feed/article-feed.js, blocks/featured-article/featured-article.css, blocks/recommended-articles/recommended-articles.css, blocks/recommended-articles/recommended-articles.js, scripts/scripts.js
style and function fixes for article feed and recommended articles
- recommended articles and article headers will appear in their own sections
- article feed and article headers now span the width of the page properly
- beginnings of string variable localization
small part of #60, #57
- https://article-feeds-styling--business-website--adobe.hlx.live/blog/
- https://article-feeds-styling--business-website--adobe.hlx.live/drafts/uncled/blog/kitchen-sink
=> refactor: article feeds

blocks/article-feed/article-feed.css, blocks/article-feed/article-feed.js, blocks/article-header/article-header.css, blocks/banner/banner.css, blocks/embed/embed.css, blocks/embed/embed.js, blocks/featured-article/featured-article.css, blocks/pull-quote/pull-quote.css, blocks/recommended-articles/recommended-articles.css, blocks/recommended-articles/recommended-articles.js, scripts/scripts.js
block cleanup, including:
- slightly more dynamic instagram embed styling
- fix pull quote and banner styles on mobile
- properly display embed block with no caption
- and general linting
small part of #60 
before: https://main--business-website--adobe.hlx.live/drafts/uncled/blog/3-marketing-predictions-for-a-cookieless-world
after: https://block-cleanup--business-website--adobe.hlx.live/drafts/uncled/blog/3-marketing-predictions-for-a-cookieless-world
=> refactor: block cleanup

blog/sitemap-index.xml
adding a sitemap-index to be included in the site's `robots.txt`
=> chore: sitemap

blocks/article-feed/article-feed.js, blocks/featured-article/featured-article.css, blocks/featured-article/featured-article.js, blocks/tag-header/tag-header.css, blocks/tag-header/tag-header.js, helix-query.yaml, scripts/scripts.js, styles/styles.css
if on tags landing page:
- tag header is auto-blocked from h1 title and image
- if tags page has featured article, article is properly styled in tag header
- article feed built below tag header
no featured article: https://tags--business-website--adobe.hlx3.page/blog/tags/digital-foundation
featured article: https://tags--business-website--adobe.hlx3.page/blog/tags/data-management
=> feat: tags landing pages

blocks/article-feed/article-feed.js, blocks/article-header/article-header.js, blocks/featured-article/featured-article.js, blocks/recommended-articles/recommended-articles.js, scripts/scripts.js
where article category appears, it is wrapped in a link to the categories page
- featured article cards
- article cards in article feeds
- article header
#77 
featured article cards, article cards in article feeds: https://article-category--business-website--adobe.hlx3.page/blog/
article header: https://article-category--business-website--adobe.hlx3.page/blog/insights/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
=> feat: link article category

blocks/article-feed/article-feed.js, blocks/article-header/article-header.js, blocks/featured-article/featured-article.js, blocks/recommended-articles/recommended-articles.js, scripts/scripts.js
1. leverage existing query index checks to ensure recommended article exists
2. only build cards for articles that exist
3. remove recommended articles container if empty
#78 
displaying only valid articles: https://block-recommended-articles--business-website--adobe.hlx3.page/blog/insights/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
no valid recommended articles: https://block-recommended-articles--business-website--adobe.hlx3.page/blog/insights/3-traits-of-award-winning-experience-makers
=> refactor: recommended articles

blocks/article-feed/article-feed.js, blocks/recommended-articles/recommended-articles.css, blocks/recommended-articles/recommended-articles.js, styles/styles.css
- button styles should mimic blog.adobe
- button text should come from variables sheet
#80 
- featured articles, load more: https://button-styles--business-website--adobe.hlx3.page/blog/
=> Button styles

blocks/article-feed/article-feed.js, blocks/article-header/article-header.js, scripts/scripts.js
=> chore: compute language and root path

scripts/scripts.js
removes empty `div`s from `main`
landing page: https://remove-empty-div--business-website--adobe.hlx3.page/blog/
tags page: https://remove-empty-div--business-website--adobe.hlx3.page/blog/categories/insights
blog post: https://remove-empty-div--business-website--adobe.hlx3.page/blog/insights/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
=> feat: remove empty divs

blocks/interlinks/interlinks.js, scripts/scripts.js, styles/lazy-styles.css
add interlinks based on keywords
#79 
- https://interlinking--business-website--adobe.hlx3.page/blog/insights/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
- https://interlinking--business-website--adobe.hlx3.page/blog/insights/japans-digital-transformation-opportunity-when-a-customer-first-culture-embraces-a-digital-first-future
=> feat: interlinking

blocks/featured-article/featured-article.js
=> feat: handle missing featured article

blocks/article-feed/article-feed.js, blocks/recommended-articles/recommended-articles.js, scripts/scripts.js
rename variables.json > placeholders.json (and related functions, variables)
=> chore: rename variables > placeholders

blocks/article-header/article-header.css
article header h1 will scale smaller for smaller screens
#92 
before: https://main--business-website--adobe.hlx3.page/blog/insights/japans-digital-transformation-opportunity-when-a-customer-first-culture-embraces-a-digital-first-future
after: https://mobile-h1--business-website--adobe.hlx3.page/blog/insights/japans-digital-transformation-opportunity-when-a-customer-first-culture-embraces-a-digital-first-future
=> refactor: scale article h1 for mobile

.github/workflows/psi.yml, .gitignore, blocks/featured-article/featured-article.css, blocks/recommended-articles/recommended-articles.css, styles/lazy-styles.css, styles/styles.css
* Update gitignore to ignore DS_Store OS files.
* Update PSI workflow to point to more resilient PSI action (should move to adobe-rnd eventually)
**Incoming commit:**
* Added better fallback font (Trebuchet MS) to reduce CLS.
* Removed 'Adobe Clean' to prevent false CLS negatives when debugging locally.
* Promoted select featured article CSS to styles.css to reduce padding shifts.
* Slightly reduced default featured article padding on mobile to prevent word wrap issues when loading fonts.
* Added recommended articles block to visibility hidden FUOC section.
* Added `opacity` to over-arching transition which will default to transforming _every_ property. PSI complained it was trying to transform borders.
=> CLS Improvements

blocks/interlinks/interlinks.js, scripts/delayed.js, scripts/scripts.js
interlink is delayed (runs after martech)
=> refactor: delay interlink

blocks/article-header/article-header.js, scripts/scripts.js
https://article-header-block--business-website--adobe.hlx.live/blog/insights/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
vs. 
https://main--business-website--adobe.hlx.live/blog/insights/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
=> fix: lcp improvement

scripts/delayed.js
adds `rel="noopener"` and `target="_blank"` to external links (existing feature on blog)
=> feat: update external links rel and target

head.html, package-lock.json, scripts/delayed.js, scripts/scripts.js
In order to optimize the performance of helix pages that have adobe analytics and target and other marketing technologies, I have split up the marketing technologies into 2 buckets: a) those that can load immediately and b) those that need to be deferred.  This allows for important things to be loaded like analytics and target, and then to delay other things like 3rd party tags to load later.
URL to test: 
https://alloy--business-website--adobe.hlx3.page/blog/?alloy=on
no related issuess
Trying to optimize performance while still loading analytics and target early and not compromising numbers for performance.
On my local machine.
=> Alloy marketingtech implementation prototype

scripts/scripts.js
https://declarative-instrumentation--business-website--adobe.hlx3.page/blog/insights/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
=> feat: declarative instrumentation

blocks/article-feed/article-feed.js, blocks/gnav/gnav-search.js, scripts/scripts.js
support for chunked index reads...
https://chunked-index--business-website--adobe.hlx3.page/blog/categories/how-to
https://chunked-index--business-website--adobe.hlx3.page/blog/
=> feat: support chunked index reads

blocks/gnav/gnav.js, scripts/scripts.js
https://relative-gnav--business-website--adobe.hlx3.page/blog/
vs. 
https://business.adobe.com/blog/
=> chore: turn internal links in gnav relative to hostname

blocks/recommended-articles/recommended-articles.css, scripts/scripts.js, styles/styles.css
https://homepage-style--business-website--adobe.hlx3.page/blog/
vs. 
https://main--business-website--adobe.hlx3.page/blog/
=> homepage style

scripts/delayed.js, scripts/scripts.js
adding listvars and link tracking to declarative instrumentation
https://listvars--business-website--adobe.hlx3.page/blog/
=> feat: add listvars and link tracking

blocks/article-header/article-header.js, blocks/tags/tags.js
https://link-adjustments--business-website--adobe.hlx.live/blog/perspectives/adobe-shoppers-have-seen-over-2-billion-out-of-stock-messages-online-october-2021
vs. 
https://main--business-website--adobe.hlx.live/blog/perspectives/adobe-shoppers-have-seen-over-2-billion-out-of-stock-messages-online-october-2021
some cleanup on tag and links an eyebrow.
=> chore: link adjustments

blocks/tag-header/tag-header.js
https://tag-header-image--business-website--adobe.hlx3.page/blog/tags/perspectives
vs. 
https://main--business-website--adobe.hlx3.page/blog/tags/perspectives
=> chore: improve quality on desktop

blog/sitemap-index.xml
https://sitemap-index--business-website--adobe.hlx3.page/blog/sitemap-index.xml
=> chore: update sitemap index

blocks/article-header/article-header.css, blocks/article-header/article-header.js, blog/sitemap-index.xml, scripts/delayed.js, scripts/scripts.js
introducing the lighthouse switch to bring things back to 100 so we can use the bots lighthouse check again...
https://lighthouse-tuning--business-website--adobe.hlx.live/blog/?lighthouse=on
https://lighthouse-tuning--business-website--adobe.hlx.live/blog/the-latest/announcing-the-2021-adobe-experience-maker-awards-finalists?lighthouse=on
=> Lighthouse tuning

blocks/footer/footer.css, blocks/footer/footer.js
address axe wcag issues in footer, including:
- add alt text to images (social, adchoices, globe)
- add `[aria-label]` to social icons
- `.footer-nav-item-title` `h4` elements replaced with appropriate `a` elements
#151 
https://axe-wcag-audit--business-website--adobe.hlx3.page/blog/
=> fix: address footer axe wcag issues

scripts/scripts.js
https://block-loader--business-website--adobe.hlx.live/blog/perspectives/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
vs. 
https://main--business-website--adobe.hlx.live/blog/perspectives/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
=> fix: handle existing loaded CSS

helix-query.yaml
=> chore: description is there twice

blocks/gnav/gnav.css, blocks/gnav/gnav.js, blocks/gnav/large-menu.css, scripts/scripts.js
* Port gnav mobile styles from blog
* Add section nav support
* Add top-level CTA button support
* https://gnav-updates--business-website--adobe.hlx3.page/drafts/cmillar/gnav/?lighthouse=on
Resolves: GH-187
=> GH-187 - Gnav Updates

scripts/delayed.js, scripts/scripts.js
https://locales--business-website--adobe.hlx3.page/uk/blog/
https://locales--business-website--adobe.hlx3.page/au/blog/
=> chore: locales

blog/sitemap-index.xml
Quick follow up to last PR, I forgot to add the sitemaps for locales to the /blog/sitemap-index.xml
=> Chore: Added sitemaps to sitemap-index.xml

scripts/scripts.js
https://alloy--business-website--adobe.hlx3.page/blog/perspectives/how-to-win-in-the-customer-intelligence-era?alloy=on
none
performance improvements
Yes, tested locally
=> Alloy updates

styles/styles.css
Quick fix for the tag headers
Test: https://tag-header-fix--business-website--adobe.hlx.page/blog/tags/the-latest
Before: https://main--business-website--adobe.hlx.page/blog/tags/the-latest
=> Tag header width fix

scripts/scripts.js, styles/styles.css
=> Fixing headings style

scripts/scripts.js, scripts/taxonomy.js
Added taxonomy translation so a KR tag can be mapped to desired URL. 
With fix: https://tags-translate--business-website--adobe.hlx.page/kr/blog/basics/all-about-content-marketing
Without: https://main--business-website--adobe.hlx.page/kr/blog/basics/all-about-content-marketing
Category above title, tags below post. 
MWPW-109009
=> Added tag translation for taxonomy

scripts/scripts.js
Adds check for running the taxonomy translation solution.
Test URL: https://tags-translate-hotfix--business-website--adobe.hlx.page/kr/blog/
Merging, but opened PR for awareness.
=> Added lang check for sites this should run on

scripts/scripts.js
Issue: [MWPW-110381](https://jira.corp.adobe.com/browse/MWPW-110381)
Current: 
https://main--business-website--adobe.hlx.page/kr/blog/
https://main--business-website--adobe.hlx.page/jp/blog/
Fixed:
https://articlecard-tagfix--business-website--adobe.hlx.page/kr/blog/
https://articlecard-tagfix--business-website--adobe.hlx.page/jp/blog/
=> Fixing bug: MWPW-110381

blocks/article-header/article-header.js, scripts/scripts.js
Fixing two issues:
1. html lang set as undefined for Korean pages.
2. Author image getting `---` URL.
Current:
https://business.adobe.com/kr/blog/the-latest/2022-adobe-digital-trends-report
Fixed:
https://author-fix--business-website--adobe.hlx.page/kr/blog/the-latest/2022-adobe-digital-trends-report
=> LANG_LOC `ko` to `kr`. and authorTaxonomy.

head.html
* Change head to allow cross origin wildcard
=> MWPW-111242 - Bacom on Milo Libs

scripts/scripts.js
* Introduce PRODUCTION_DOMAINS constant to match boilerplate
* Add loadLibs to get list of Milo blocks
* Change loadBlock to use Milo libs blocks
* Will fallback to local blocks if milo libs are not available
Resolves: [MWPW-111242](https://jira.corp.adobe.com/browse/MWPW-111242)
Test URLs:
**Test URLs:**
- Before: https://main--business-website--adobe.hlx.page/
- After: https://libs--business-website--adobe.hlx.page/
=> MWPW-111242 - Onboard to Milo Libs

styles/styles.css
Adds style to columns to contain within the main content section area.
MWPW-111435
Test URL:
Before: 
https://main--business-website--adobe.hlx.page/blog/the-latest/announcing-done-right-live-tour
After:
https://table-patch-style--business-website--adobe.hlx.page/blog/the-latest/announcing-done-right-live-tour
=> Basic container width style for columns

blocks/banner/banner.css, blocks/banner/banner.js
Current:
https://main--business-website--adobe.hlx.page/kr/blog/the-latest/2022-adobe-digital-trends-report
Test:
https://banner-fix--business-website--adobe.hlx.page/kr/blog/the-latest/2022-adobe-digital-trends-report
*There is still CORS issue from blog.adobe.com. You should see the banner only when CORS extension enabled for now.
=> support for new translation banner.

scripts/delayed.js, scripts/scripts.js
Resolving issue: [MWPW-112500](https://jira.corp.adobe.com/browse/MWPW-112500)
Before: https://main--business-website--adobe.hlx.page/drafts/seanchoi/nofollow-links-demo
After: https://nofollow-link--business-website--adobe.hlx.page/drafts/seanchoi/nofollow-links-demo?milolibs=nofollow-move
This should be merged after https://github.com/adobecom/milo/pull/58 get merged.
=> Adding nofollow feature from Milo.

scripts/delayed.js, scripts/scripts.js
This is followup PR from https://github.com/adobe/business-website/pull/221
Resolving issue: [MWPW-112500](https://jira.corp.adobe.com/browse/MWPW-112500)
Before: https://main--business-website--adobe.hlx.page/drafts/seanchoi/nofollow-links-demo
After: https://nofollow-link--business-website--adobe.hlx.page/drafts/seanchoi/nofollow-links-demo
=> Nofollow link

blog/scripts/canary.js
=> canary for blog move

blog/scripts/delayed.js, blog/scripts/scripts.js
**Opened Issue**: [MWPW-116284](https://jira.corp.adobe.com/browse/MWPW-116284)
**Testing URL**:
Before: https://main--business-website--adobe.hlx.page/blog/banners/adobe-trust-report-2022-apac
After: https://path-fix--business-website--adobe.hlx.page/blog/banners/adobe-trust-report-2022-apac
**Testing Note**: You will need to set your network throttling as `Fast 3G` to reproduce the issue.
=> Fixing issue with /au/au/

blog/blocks/tags/tags.js
Excludes 'fpost' tag from display. 
[MWPW-115458](https://jira.corp.adobe.com/browse/MWPW-115458)
Test URLS:
https://main--business-website--adobe.hlx.page/drafts/bradjohn/output/priority-management
https://fpost-hide--business-website--adobe.hlx.page/drafts/bradjohn/output/priority-management
=> Excluded fpost tag from display

fstab.yaml
=> Sharepoint hotfix
