adobe/business-website

blocks/pull-quote/pull-quote.css
blocks/pull-quote/pull-quote.js

This will do for Pull quote block.
For QA:
https://block-pull-quote--business-website--adobe.hlx3.page/drafts/uncled/blog/kitchen-sink#pull-quote-block
https://github.com/adobe/business-website/issues/5
This is requested by David Nuescheler.
There is no test plan added for this block.
I would add test case that \<p\> with quote replaces with \<h2\>
The styles are not exactly same as blog.adobe.com's example, because some of styles should be applied more in higher level than block. (like font-famaily). I believe this should good enough for now.
End result:

block: pull-quote

---

blocks/images/images.css
blocks/images/images.js

- `picture` tags in images block are placed in `figure` tags
- if images block has a caption (italic text in block), caption is placed in `figcaption`
- if images block has a link, `picture` is wrapped in `a`
#6 
semantically link images to captions, mimic blog initial styling
images block with caption and link
images block with side-by-side images with captions (2- and 3-column supported)

Block images initial setup and styling

---

blocks/images/images.css
blocks/images/images.js
scripts/scripts.js
styles/styles.css

- remove styling (`strong`, `em`) from inline `picture`s (images not in image blocks)
- places images (and captions, if applicable) in image block structure to prep for `decorateBlock` functionality
#16 
all images (whether inline or in image blocks) will appear on screen the same (semantically and stylistically)
inline image with following caption
inline image without caption

feat: prep inline images for image block styling

---

blocks/images/images.css
blocks/images/images.js
scripts/scripts.js
styles/styles.css

- export `buildFigure` function
- globalize `.caption` styles
- build hero block > place hero image in `figure` (add caption if applicable) > place hero block after `h1` container
#13 
build structure for hero images, mimic blog style
hero image with caption (no caption also supported)
** note: definitely not correct spacing between `h1` and hero block, styling `h1` outside the scope of this PR

feat(hero): build and style hero img

---

blocks/article-header/adobe-logo.svg
blocks/article-header/article-header.css
blocks/article-header/article-header.js
scripts/scripts.js

- created new default/fallback image that adheres to style guide
- replace default/fallback `img` with image container `div` (image appears as `background-image`)
- adds author image in image container
#48 
https://author-img--business-website--adobe.hlx3.page/drafts/uncled/blog/agility-empathy-purpose-steered-mastercard-during-pandemic

refactor: add default/fallback img

---

blocks/article-header/article-header.css
styles/styles.css

- use the horizontal auto margins on the `<div>`s inside the `.section-wrapper` elements
- correct font weight/size for elements inside `<main>`
- allow full-width expansion for `.article-header`
#53 
https://lists-formatting--business-website--adobe.hlx3.page/blog/trends/announcing-the-2021-adobe-experience-maker-awards-finalists

Lists formatting

---

blocks/article-feed/article-feed.js
blocks/article-header/article-header.js
blocks/featured-article/featured-article.js
blocks/gnav/gnav.js
blocks/recommended-articles/recommended-articles.js
scripts/scripts.js

i am testing a more general change to the webp fallback...
https://webp-fallback--business-website--adobe.hlx3.page/blog/
https://webp-fallback--business-website--adobe.hlx3.page/blog/trends/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
unfortunately i don't have access to a pre webp browser to see if the fallback works.
@fkakatie i changed a few things around in the author image code, i am sure that this is by no means ideal, but i think the structure may change anyway towards using a bg image for the real fallback instead of the current js based solution.
@rofe @kptdobe i think we should look at this in light of a more whole sale change across all projects and helix.

feat(webp): refactor webp fallback in prep for markup change

---

scripts/scripts.js

`.article-header` block should appear in its own `section > div.section-wrapper` container. 
in `buildArticleHeader` func:
- `.buildArticleHeader` block is nested in containing `<div>`
- `.buildArticleHeader` is prepended to the `<main>` element
slight change in existing structure as described above enables existing functionality (`wrapSections`, `decorateBlocks`) to position `.buildArticleHeader` correctly in the DOM with appropriate classes
- https://article-header--business-website--adobe.hlx3.page/blog/trends/back-to-school-2021-how-digital-technologies-can-ease-the-return-to-in-person-education
- https://article-header--business-website--adobe.hlx3.page/blog/trends/improving-the-customer-experience-cios-look-beyond-business-technology-to-privacy
- …

refactor(article-header): place article header in separate section

---

styles/styles.css

fix styling of `div`s and non-`div`s inside `.section-wrapper` 
:warning: **NOTE:** other styling appears to be negatively impacted by change to recommended articles styling in previous PR -- will correct in future PR
small piece of #60 
https://section-wrapper-styling--business-website--adobe.hlx.live/drafts/uncled/blog/kitchen-sink

refactor: fix section wrapper styles

---

blocks/animation/animation.css
blocks/images/images.css
blocks/infographic/infographic.css
styles/styles.css

fixes figures and captions
:warning: **NOTE:** other styling appears to be negatively impacted by change to recommended articles styling in previous PR -- will correct in future PR
small part of #60 
https://block-caption-styling--business-website--adobe.hlx.live/drafts/uncled/blog/kitchen-sink

refactor: block and caption styling

---

helix-query.yaml

I started sitemap generation manually in that branch, please verify in S3:
https://s3.console.aws.amazon.com/s3/object/helix-content-bus?region=us-east-1&prefix=3621075ee7af54c8c98bdbc290124eb327918dff08030d03aed2ce29266/live/blog/sitemap.xml

feat: add sitemap definition

---

helix-query.yaml

adds the `<meta name="robots" content="...">` value to the index

fix: add robots column

---

blocks/tags/tags.css
blocks/tags/tags.js
scripts/scripts.js

- `getMetadata` function now queries for all name/property matches, still returns a string
- tags block is built from `article:tag` metadata as part of autoblocking
- tag block is decorated in the same way as other blocks with the `decorateBlock` functionality
https://tags-block--business-website--adobe.hlx3.page/blog/news/bon-voyage-embarking-on-journeys-that-guests-love
articles without tags are unaffected 
https://tags-block--business-website--adobe.hlx3.page/blog/trends/isobar-helps-mitsubishi-motors-australia-drive-new-car-buying-journey

feat: tags block

---

helix-query.yaml

query index should populate tags in lieu of topics

refactor: update query for tags

---

helix-query.yaml

query multiple values for article tags

chore: target all article:tag values

---

styles/lazy-styles.css

on image error in article card, alt text was impossible to read
before:
after:

chore: make alt text visible in fallback

---

blocks/animation/animation.js

animation block was previously built to transform hlx.blob links
propose that animation block transform hlx.blob links and handle new-style helix bot uploads
#95 
before: https://main--business-website--adobe.hlx3.page/drafts/fkakatie/authoring-a-blog-post#animation
after: https://block-animation--business-website--adobe.hlx3.page/drafts/fkakatie/authoring-a-blog-post#animation

refactor: allow for new and old hlx bot uploads

---

blocks/article-header/article-header.css
scripts/scripts.js

- fix author img styles
- auto-block article header without author
no author before: https://main--business-website--adobe.hlx3.page/blog/insights/emotional-analytics
no author after: https://article-header--business-website--adobe.hlx3.page/blog/insights/emotional-analytics
author img before: https://main--business-website--adobe.hlx3.page/blog/news/agility-empathy-purpose-steered-mastercard-during-pandemic
author img after: https://article-header--business-website--adobe.hlx3.page/blog/news/agility-empathy-purpose-steered-mastercard-during-pandemic

refactor: article header

---

scripts/scripts.js

~~featured images in article header were using 750px width~~
~~propose first image to be optimized uses 2000px width~~
correct default media query
images in cards are unaffected
before: https://main--business-website--adobe.hlx3.page/blog/basics/digital-success-for-small-businesses-with-adobe-sign
after: https://larger-first-img--business-website--adobe.hlx3.page/blog/basics/digital-success-for-small-businesses-with-adobe-sign

refactor: first img  uses larger width

---

blocks/recommended-articles/recommended-articles.css

before: https://main--business-website--adobe.hlx3.page/blog/
after: https://small-rec-article-padding--business-website--adobe.hlx3.page/blog/

fix: update padding in small recommended article block

---

blocks/recommended-articles/recommended-articles.css

remove description from recommended articles (small) 
#133 
before: https://main--business-website--adobe.hlx3.page/blog/
after: https://small-rec-articles--business-website--adobe.hlx3.page/blog/

fix: remove description on small featured articles block

---

blocks/tag-header/tag-header.css
scripts/scripts.js

tags pages have new doc format in line with adobe.blog, update code to read new format
before: https://main--business-website--adobe.hlx3.page/blog/tags/basics
after: https://tags-pages--business-website--adobe.hlx3.page/blog/tags/basics

fix: update tags header for new doc format

---

head.html
scripts/scripts.js

refactoring prehide to take `target` metadata into configuration, only if target is turned on via metadata, prehide is active and target is loaded.
https://prehide-refactor--business-website--adobe.hlx.live/blog/
https://prehide-refactor--business-website--adobe.hlx.live/drafts/uncled/blog/25-years-evolution-technology-changed-lives
this should also take care of the `SI` issue. interestingly enough, i see on `PSI` an `LCP` issue that i am not able to reproduce, in my browser.

feat: selective target loading and unhiding

---

blocks/featured-article/featured-article.js
blocks/recommended-articles/recommended-articles.js
scripts/scripts.js

due to last minute changes the `recommend-articles` and `featured-article` references are no longer correct, so i temporarily put in a path rewriter to avoid having to go and change all the URLs short term...
compare:
https://path-rewrite--business-website--adobe.hlx3.page/blog/
vs. 
https://main--business-website--adobe.hlx3.page/blog/

chore: path rewrite

---

scripts/scripts.js

https://categories-cleanup--business-website--adobe.hlx3.page/blog/
vs
https://main-cleanup--business-website--adobe.hlx3.page/blog/
categories link on cards

chore: update categories to tags

---

scripts/scripts.js

store placeholders in window obj to reduce repeat calls
#134 
https://cache-placeholders--business-website--adobe.hlx3.page/blog/

fix: store placeholders in window obj to reduce repeat calls

---

blocks/tags/tags.js

see `documents and e-signatures` tag link at the bottom
https://tags-urls--business-website--adobe.hlx3.page/blog/how-to/quick-guide-to-digitizing-liability-waivers-in-education
vs.
https://main--business-website--adobe.hlx3.page/blog/how-to/quick-guide-to-digitizing-liability-waivers-in-education

chore: better tag url construction

---

scripts/delayed.js

Errors are visible in the console when executing the `updateExternalLinks` method. This is because some of the anchors don't have a valid href and `new URL(a)` will fail.
The fix will check for href existence before doing a `new URL(a)`.
https://link-issue--business-website--adobe.hlx3.page/blog/
#167 
Issue is breaking the script and PrivacyJS is not loaded anymore.
locally

fix: handle anchors without href when updating external links

---

blocks/footer/footer.js

- add `tabindex` to "Change language" button, footer nav item titles on small screens 
- add `aria-label` to "Change language" button
- add `Enter` and `Space` event listeners to "Change language" button, footer nav item titles on small screens 
- add `aria-current=page` to currently selected "Change language" option
[#131](https://github.com/adobe/blog/issues/131) on blog, approved and merged PR [#141](https://github.com/adobe/blog/pull/141)
https://footer-accessibility--business-website--adobe.hlx.live/blog/
https://footer-accessibility--business-website--adobe.hlx3.page/blog/

fix: import footer accessibility from blog

---

blocks/embed/embed.js

Adding the block-visible class on the loadEmbed function.
Testing URL: 
https://embed-show--business-website--adobe.hlx3.page/blog/perspectives/four-dashboards-digital-b2b-merchants-should-be-watching
https://github.com/adobe/business-website/issues/181
https://github.com/adobe/business-website/issues/180
- [x ] Bug fix (non-breaking change which fixes an issue)

Show embed blocks on render

---

blocks/embed/embed.js

In some cases the addEventListener('load') was not being picked up, causing embeds to not render. Adding readyState check fixes the inconsistency. 
Fixes https://github.com/adobe/business-website/issues/184
https://embed-inconsistent-load--business-website--adobe.hlx3.page/blog/perspectives/four-dashboards-digital-b2b-merchants-should-be-watching

Added readyState complete check to addEventListener

---

helix-query.yaml
helix-sitemap.yaml

For setting up region sites query index and sitemaps.
- Excluding base /blog content in query index
- Following pattern of keeping sitemaps for different regions in /blog/sitemap-{xx}.xml

Added FR, DE, JP, and KR to config

---

tools/sidekick/config.js

Enable the sidekick on production URLs.

chore: update sidekick config

---

scripts/delayed.js

On all https://business.adobe.com/blog/ pages, there is this error in the console: 
```
scripts.js:965 Mixed Content: The page at 'https://business.adobe.com/blog/' was loaded over HTTPS, but requested an insecure script 'http://geo2.adobe.com/json/?callback=setLinksToGeo'. This request has been blocked; the content must be served over HTTPS.
```
Request to http://geo2.adobe.com/json/?callback=setLinksToGeo and https://geo2.adobe.com/json/?callback=setLinksToGeo seems to return the same result, why not using the https version ?
Test page: https://fix-mixed-content--business-website--adobe.hlx3.page/blog/

fix: use https for geo linker

---

scripts/scripts.js
styles/styles.css

This PR goes with https://github.com/adobecom/milo/pull/53
- Enabling table option for column block.
- Getting variables.css from Milo CSS variables when Milo block gets loaded.
Resolves: [MWPW-111569](https://jira.corp.adobe.com/browse/MWPW-111569)
Test URLs:
https://column-fix--business-website--adobe.hlx.page/drafts/seanchoi/milo-test?milolibs=column-table
From Current:
Before: https://column-fix--business-website--adobe.hlx.page/blog/basics/business-case
After: https://column-fix--business-website--adobe.hlx.page/blog/basics/business-case?milolibs=column-table

Column fix

---

tools/importer/glossary_import.js

Added the helix importer script for importing/migrating the glossary pages to the BACOM blog.
- Added glossary_import.js helix importer script.
[MWPW-107525](https://jira.corp.adobe.com/browse/MWPW-107525)
Test URLs:
- Before: https://main--business-website--adobe.hlx.page/blog/basics/account-based-marketing
- After: https://glossary-importer--business-website--adobe.hlx.page/blog/basics/account-based-marketing
Necessary change for migrating over 90 glossary pages from business.adobe.com/glossary to business.adobe.com/blog.  The original glossary pages were done in AEM whereas the BACOM blog site is Helix.
This has been tested by running the helix-webui-importer tool found [here](github.com/kptdobe/helix-webui-importer). I ran all 90 AEM based business.adobe.com/glossary URLs through the …

Added helix importer script for glossary pages

---

blocks/banner/banner.js

Makes links in the banner block relative to the site.  Otherwise links to hlx.page will break on prod.
Manual testing.
- [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] All new and existing tests passed.

Make links in banner blocks relative

---

blog/scripts/scripts.js
helix-query.yaml

Resolving issue: [MWPW-114484](https://jira.corp.adobe.com/browse/MWPW-114484)
Testing
Before: https://main--business-website--adobe.hlx.page/drafts/seanchoi/recommended-articles-testing-page
After: https://h1-title-card--business-website--adobe.hlx.page/drafts/seanchoi/recommended-articles-testing-page
QA Note, for feeds page such as https://h1-title-card--business-website--adobe.hlx.page/blog/tags/basics won't work until this get merged since they use query-index.xlsx. I am just hoping https://github.com/adobe/business-website/pull/233/files#diff-2fde5d2508ed34a1f6ec8ec4ce8133096d591a7d5901c702a0e2e558589f7265R26-R29 would work for this because I haven't found a good way to test..

Support h1 to be the title of article cards.

---

blog/blocks/banner/banner.js

Fixes first element of `<picture>` element broken in any banner promotion block. 
[MWPW-122481](https://jira.corp.adobe.com/browse/MWPW-122481)
Before: (near footer)
https://business.adobe.com/jp/blog/the-latest/dx-2022-webinar-pharmaceutical-202209
After:  (near footer)
https://bugfix-banner-images--business-website--adobe.hlx.page/jp/blog/the-latest/dx-2022-webinar-pharmaceutical-202209

MWPW-122481: URL fix for banner images
